[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nodejs]
command=node server.js
directory=/usr/src/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nodejs_err.log
stdout_logfile=/var/log/supervisor/nodejs_out.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx_err.log
stdout_logfile=/var/log/supervisor/nginx_out.log
